### ISSUE TITLE
Problem with Mesa/GLSL

### ISSUE THREAD

**Issue by mariobl** [gottcode/tetzle#3]
Hi, 
I've compiled  Tetzle on Fedora 21 and it starts. I can choose a jpg file and it is opened in the overview window. But the creation of the puzzle parts doesn't work. I get the following issues in the terminal:

[mariobl@localhost ~]$ tetzle
QGLShader::compile(Vertex): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

QGLShader::compile(Fragment): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

QGLShader::compile(Vertex): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

QGLShader::compile(Fragment): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

QGLShader::compile(Vertex): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

QGLShader::compile(Fragment): 0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

The package has the following dependencies:

$ rpm -qpR tetzle-2.0.3-2.fc21.x86_64.rpm
/bin/sh
/bin/sh
/bin/sh
libGL.so.1()(64bit)
libQt5Core.so.5()(64bit)
libQt5Gui.so.5()(64bit)
libQt5OpenGL.so.5()(64bit)
libQt5Widgets.so.5()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)

What can I do? In particular, which package it refers to? Maybe I can compile it using a different package?

**Comment by gottcode** [comment]
You can try running it with ```--graphics-layer=21``` or ```--graphics-layer=15``` and see if that works.

**Comment by mariobl** [comment]
It works with --graphics-layer=21, but what can I do to build a fully functional binary package? Well, I could add a start script or change the *.desktop file. Bur it there any way to give qmake any options at build time?

**Comment by gottcode** [comment]
You built a fully functional binary package. Your Mesa is reporting that it supports a higher version of GLSL than it actually does, and Tetzle is auto-detecting that. Tetzle has runtime support for different versions of OpenGL, no compile-time options.

**Comment by mariobl** [comment]
»You can set the parameter GraphicsLayer=21 under the [General] section of the config file ~/.config/GottCode/Tetzle to make it always use OpenGL 2.1 without passing it a parameter.«

OK, this works for a certain user, but it is not applicable to a binary package. Tetzle doesn't have a system-wide configuration where this could be set globally. Either I wait for a solution from the Mesa packagers [1] or I patch the *.desktop file. However, this is just a workaround, no final solution.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1194217

**Comment by gottcode** [comment]
My Mesa works just fine with open source drivers; it reports the correct version of GLSL supported by my video card. I'm not sure why yours is incorrectly reporting a higher version of GLSL than it supports. You can patch the .desktop file, but it won't be necessary for all users.

**Comment by mariobl** [comment]
Well, not necessary for everybody, but as long as the --graphics-layer option doesn't cause problems for users where it is actually not needed, then I have no problem to patch the *.desktop file as a temporary workaround.
