### ISSUE TITLE
QT5 support

### ISSUE THREAD

**Issue by MirceaKitsune** [gottcode/tetzle#5]
As someone who cares about compatibility and software being up to date with the latest libs, I decided to open an issue about qt5 support. Is there any hope of seeing a migration from qt4 to the latest qt5?

**Comment by gottcode** [comment]
Tetzle already supports Qt 5. I have not made a Windows or Mac release with Qt 5, but the lates release can use Qt 5 in Linux. And git master only supports Qt 5.
