### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by MirceaKitsune** [gottcode/tetzle#6]
Playing Tetzle with my favorite images is a great way to pass the time on my computer! I'd love being able to do the same on my Android smartphone, when I'm away and need something to keep my mind busy with. There are several jigsaw games on Google Play... but apart from being adware infested, none are as polished and fun in my book.

So here's an issue for discussing Android support, and when and if it can be expected. My suggested touchscreen controls would be: Quickly tap a piece to rotate it, tap and hold it to move it.

**Comment by gottcode** [comment]
I'm sorry to disappoint, but I will not be adding Android support to any of my projects.
